### PR TITLE
Alpha Project Structure

### PR DESCRIPTION
**Pull request by APorterCSUMB**
@MLopezCSUMB @fishgum @dw1lson 

First PR! Lots of new material, this should put the project in ALPHA status, can I get questions/comments and then approval? Self-Approving PR is not allowed in this group, all must go through team wide CR.

### CODE REVIEW

**Comment by APorterCSUMB** [comment]
Sorry - PR #2!

**Comment by dw1lson** [comment]
Looks great Andrew!

**Comment by APorterCSUMB** [comment]
@dw1lson glad you like it!
`if(happyWithCode){
    mergePR();
}`

**Comment by dw1lson** [comment]
There was a conflict in the READ.me, it looked like you had some markup notes.
I just kept it all in there.

**Comment by APorterCSUMB** [comment]
Correct - sorry about that. Setting up our page on GitHub and it
auto-committed to the master branch :-(

**Pull request merged**
